#!/usr/bin/env ruby
require 'paru/filter'

testkey = 'author'
insertKey = 'name'

Paru::Filter.run do
  if metadata.has_key?(testkey)
    nau = nil
    au = metadata[testkey]
    if au.is_a?(String)
        nau = [ Hash[ insertKey => au ] ]
    elsif au.is_a?(Array)
        if au[0].is_a?(String)
          nau = Array.new(au.length) {Hash.new}
          au.each_index { |i| nau[i] = Hash[ insertKey => au[i] ] }
        end
    end
    if not nau.nil?
      metadata[testkey] = nau
    end
    stop!
  end
end
