#!/usr/bin/env ruby
require 'byebug/core'
require 'byebug'
PORT = 8989
STDOUT.puts "\n!!!---DEBUG Server started on localhost:#{PORT} @ " + Time.now.to_s + "\n\n"
Byebug.wait_connection = true
Byebug.start_server('127.0.0.1', PORT)
byebug
require 'paru/filter'

Paru::Filter.run do
  if metadata.has_key?('author')
    au = metadata['author']
    case au.class
      when is_a?(String)
        warn "It's a string"
        nau = Hash["name" => au]
        metadata['author'] = nau
      when is_a?(Array)
        warn "It's an array"
      when is_a?(Hash)
        warn "It's a hash"
      else

    end
  end
end
