#!/usr/bin/env ruby
# require 'byebug/core'
# require 'byebug'
# PORT = 8989
# warn "\n!!!DEBUG Server started: localhost:#{PORT} @ " + Time.now.to_s + "\n\n"
# Byebug.wait_connection = true
# Byebug.start_server('127.0.0.1', PORT)
require 'paru/filter'

testkey = 'author'
insertKey = 'name'

Paru::Filter.run do
  if metadata.has_key?(testkey)
    nau = nil
    au = metadata[testkey]
    if au.is_a?(String)
        warn 'It is a string'
        nau = [ Hash[ insertKey => au ] ]
    elsif au.is_a?(Array)
        warn 'It is an array'
        if au[0].is_a?(String)
          nau = Array.new(au.length) {Hash.new}
          au.each_index { |i| nau[i] = Hash[ insertKey => au[i] ] }
        end
      else
        warn 'Who knows?'
    end
    if not nau.nil?
      metadata[testkey] = nau
    end
    stop!
  end
end
