#!/usr/bin/env ruby
#encoding: utf-8

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

input = $stdin.read
# this regex matches {Letter ... Number} should get endnote refs but not overmatch, replace with brackets
output = input.gsub(/(?:\{)([\p{Alpha}][^\}]+?)(?:(?<=[0-9])\})/, '[\1]')
#this converts to @authorYear pandoc format
output.gsub!(/([\p{Alpha}][\p{Alnum}\s-]+)(?:,\s)(\d{4})(?:\s#\d+)/) { | str | str = "@" + $1.tr(' ', '').downcase + $2 }
#this combines adjacent pandoc refs tigether
output.gsub!(/\]\[@(?=\p{Alpha})/) { | str | str = "; @" }

puts output
