# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.append_keymap]]
on = "<F8>"
run = "remove"
desc = "Trash selected files"

[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

[[mgr.prepend_keymap]]
on   = "<C-p>"
run = 'shell -- qlmanage -p "$@"'
desc = "Quick Look selected files"

[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "elvish" --block'
desc = "Open Elvish here"

[[mgr.prepend_keymap]]
on = "@"
run = 'shell --block --interactive --cursor=0 "$@"'
desc = "Run command"

[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "p" ]
run  = "plugin compress -p"
desc = "Archive selected files (password)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "h" ]
run  = "plugin compress -ph"
desc = "Archive selected files (password+header)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "l" ]
run  = "plugin compress -l"
desc = "Archive selected files (compression level)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "z" ]
run  = "plugin compress '-l 7z'"
desc = "7zip selected files (compression level)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "u" ]
run  = "plugin compress -phl"
desc = "Archive selected files (password+header+level)"

[[mgr.prepend_keymap]]
on  = [ "M", "d" ]
run = "plugin mount"

[[mgr.prepend_keymap]]
on = ["M","m"] 
run = "plugin sshfs -- mount --jump"  
desc = "Mount & jump"

[[mgr.prepend_keymap]]
on = ["M","u"]
run = "plugin sshfs -- unmount"
desc = "Unmount SSHFS" 

[[mgr.prepend_keymap]]
on = ["M","r"]
run = "plugin sshfs -- remove"        
desc = "Remove SSH host"

[[mgr.prepend_keymap]]
on = ["M","h"]
run = "plugin sshfs -- home"
desc = "Go to mount home"

[[mgr.prepend_keymap]]
on = ["M","c"]
run = "cd ~/.ssh/"                 
desc = "Go to ssh config"

[[mgr.prepend_keymap]]
on = ["g","m"]
run = "plugin sshfs -- jump"
desc = "Jump to mount"

# sudo touch/mkdir
[[mgr.prepend_keymap]]
on = ["R", "a"]
run = "plugin sudo -- create"
desc = "sudo create"

# sudo delete
[[mgr.prepend_keymap]]
on = ["R", "D"]
run = "plugin sudo -- remove --permanently"
desc = "sudo delete"

# sudo mv
[[mgr.prepend_keymap]]
on = ["R", "r"]
run = "plugin sudo -- rename"
desc = "sudo rename"

# sudo cp/mv
[[mgr.prepend_keymap]]
on = ["R", "p"]
run = "plugin sudo -- paste"
desc = "sudo paste"

# sudo cp/mv --force
[[mgr.prepend_keymap]]
on = ["R", "P"]
run = "plugin sudo -- paste --force"
desc = "sudo paste force"

# sudo ln -s (absolute-path)
[[mgr.prepend_keymap]]
on = ["R", "l"]
run = "plugin sudo -- link"
desc = "sudo link"

# sudo ln -s (relative-path)
[[mgr.prepend_keymap]]
on = ["R", "r"]
run = "plugin sudo -- link --relative"
desc = "sudo link relative path"

# sudo ln
[[mgr.prepend_keymap]]
on = ["R", "L"]
run = "plugin sudo -- hardlink"
desc = "sudo hardlink"




