# Inserts a blank line between shell prompts
add_newline = true

[character] 
success_symbol = "[▶︎](bold green)"
error_symbol = "[▷](bold red)"

#[env_var]
#variable = "PLATFORM"
#default = ""

[shlvl]
symbol = "↯"
style = "dimmed yellow"
disabled = true

[shell]
bash_indicator = "b"
zsh_indicator = "z"
elvish_indicator = "e"
style = "dimmed gray"
disabled = false

[hostname]
format = "[$hostname]($style) » "
ssh_only = false

[memory_usage]
disabled = false

[directory]
truncation_symbol = "…/"

[battery]
[[battery.display]]
threshold = 10
style = "bold red"
[[battery.display]]
threshold = 30
style = "bold yellow"
discharging_symbol = "⌁"
