#!/usr/bin/env ruby -w
# ROT13 - Takes STDIN and encrypts it using ROT13.
# Created by Patrick Gibson - Friday October 13, 2006 - 12:00 AM

def swapLetter(byte)
  if /[A-M]|[a-m]/ === byte.chr then byte += 13
  else byte -= 13 end
end

STDIN.each_byte do |byte|
  byte = swapLetter(byte) if /[A-Z]|[a-z]/ =~ byte.chr
  STDOUT.putc byte.chr.to_s
end
